using AsmResolver.DotNet;
using AsmResolver.DotNet.Signatures;
using AsmResolver.DotNet.Signatures.Types;

namespace Bannerlord.ReferenceAssemblies;

/// <summary>One managed assembly of a build, and the module folder it came from; null for the engine under bin/.</summary>
internal sealed record GameAssembly(string Path, string? Module, ModuleDefinition Definition)
{
    public string FileName => System.IO.Path.GetFileName(Path);
}

/// <summary>
/// The managed assemblies of a build, loaded once for both the movie scan and the type schema, with an
/// index that resolves a type or member reference to its definition anywhere in the build. References
/// are resolved by name rather than through AsmResolver's resolver, which would go looking for the
/// framework and every third-party library; only what the build itself defines matters here.
/// </summary>
internal sealed class GameAssemblies
{
    private readonly Dictionary<string, TypeDefinition> _types = new(StringComparer.Ordinal);
    private readonly Dictionary<(string Assembly, string Type), TypeDefinition> _typesByAssembly = [];
    private readonly Dictionary<TypeDefinition, GameAssembly> _owners = [];
    private readonly Dictionary<string, List<TypeDefinition>> _derived = new(StringComparer.Ordinal);
    private readonly Dictionary<string, List<TypeDefinition>> _implementers = new(StringComparer.Ordinal);

    public IReadOnlyList<GameAssembly> Assemblies { get; }

    public GameAssemblies(IEnumerable<(string Path, string? Module)> files)
    {
        var assemblies = new List<GameAssembly>();
        foreach (var (path, module) in files.OrderBy(x => x.Module ?? "", StringComparer.OrdinalIgnoreCase).ThenBy(x => x.Path, StringComparer.OrdinalIgnoreCase))
        {
            ModuleDefinition definition;
            try
            {
                definition = ModuleDefinition.FromFile(path);
            }
            catch (Exception)
            {
                // A native library, or a file that is not an assembly at all.
                continue;
            }
            if (definition.Assembly is null)
                continue;
            assemblies.Add(new GameAssembly(path, module, definition));
        }
        Assemblies = assemblies;

        foreach (var assembly in Assemblies)
        foreach (var type in assembly.Definition.GetAllTypes())
        {
            var fullName = type.FullName;
            // The first of two same-named types wins; a reference that names its assembly still finds the other.
            _types.TryAdd(fullName, type);
            _typesByAssembly.TryAdd((assembly.Definition.Assembly!.Name?.ToString() ?? "", fullName), type);
            _owners[type] = assembly;
        }

        foreach (var type in _owners.Keys)
        {
            if (type.BaseType is { } baseType && BaseName(baseType) is { } name)
                _derived.GetOrAdd(name, () => []).Add(type);
            foreach (var implemented in type.Interfaces)
                if (implemented.Interface is { } face && BaseName(face) is { } faceName)
                    _implementers.GetOrAdd(faceName, () => []).Add(type);
        }
    }

    /// <summary>
    /// The managed assemblies of a game folder: the engine's under bin/&lt;platform&gt;/ and every module's under
    /// Modules/&lt;module&gt;/bin/&lt;platform&gt;/. The AutoGenerated ones are compiled from the same XML and only
    /// serve as a check, so they are listed apart.
    /// </summary>
    public static (List<(string Path, string? Module)> Scanned, List<(string Path, string? Module)> Generated) Find(string gameFolder, IReadOnlyList<string> binFolders)
    {
        var all = new List<(string Path, string? Module)>();
        foreach (var bin in binFolders)
        {
            var engine = Path.Combine(gameFolder, "bin", bin);
            if (Directory.Exists(engine))
                all.AddRange(Directory.EnumerateFiles(engine, "*.dll").Select(x => (x, (string?) null)));

            var modules = Path.Combine(gameFolder, "Modules");
            if (!Directory.Exists(modules))
                continue;
            foreach (var module in Directory.EnumerateDirectories(modules))
            {
                var folder = Path.Combine(module, "bin", bin);
                if (Directory.Exists(folder))
                    all.AddRange(Directory.EnumerateFiles(folder, "*.dll").Select(x => (x, (string?) Path.GetFileName(module))));
            }
        }

        // One file per name, as the reference packages take them: several platform folders carry the same assemblies.
        var unique = all.GroupBy(x => (x.Module, Path.GetFileName(x.Path))).Select(x => x.First()).ToList();
        var generated = unique.Where(x => IsAutoGenerated(x.Path)).ToList();
        return (unique.Where(x => !IsAutoGenerated(x.Path)).ToList(), generated);
    }

    public static bool IsAutoGenerated(string path) => Path.GetFileName(path).Contains(".AutoGenerated", StringComparison.OrdinalIgnoreCase);

    public IEnumerable<TypeDefinition> Types => _owners.Keys;

    public GameAssembly? OwnerOf(TypeDefinition type) => _owners.GetValueOrDefault(type);

    /// <summary>The build's definition of a type, or null for one outside the build.</summary>
    public TypeDefinition? Resolve(ITypeDefOrRef? type)
    {
        switch (type)
        {
            case null:
                return null;
            case TypeDefinition definition:
                return definition;
            case TypeSpecification { Signature: GenericInstanceTypeSignature generic }:
                return Resolve(generic.GenericType);
            case TypeSpecification specification:
                return Resolve(specification.Signature?.GetUnderlyingTypeDefOrRef());
        }

        var fullName = type.FullName;
        if (type.Scope?.GetAssembly()?.Name?.ToString() is { } assembly && _typesByAssembly.TryGetValue((assembly, fullName), out var exact))
            return exact;
        return _types.GetValueOrDefault(fullName);
    }

    public TypeDefinition? Resolve(TypeSignature? signature) => signature switch
    {
        null => null,
        GenericInstanceTypeSignature generic => Resolve(generic.GenericType),
        TypeDefOrRefSignature plain => Resolve(plain.Type),
        _ => null,
    };

    public TypeDefinition? FindType(string fullName) => _types.GetValueOrDefault(fullName);

    /// <summary>The types whose base type is the given one, directly.</summary>
    public IReadOnlyList<TypeDefinition> DirectlyDerived(TypeDefinition type) =>
        _derived.TryGetValue(type.FullName, out var list) ? list : [];

    /// <summary>The type and every type deriving from it anywhere in the build.</summary>
    public IEnumerable<TypeDefinition> SelfAndDerived(TypeDefinition type)
    {
        var seen = new HashSet<TypeDefinition>();
        var queue = new Queue<TypeDefinition>([type]);
        while (queue.TryDequeue(out var next))
        {
            if (!seen.Add(next))
                continue;
            yield return next;
            foreach (var derived in DirectlyDerived(next))
                queue.Enqueue(derived);
        }
    }

    /// <summary>
    /// The classes an object declared as this type can be: the type and everything deriving from it, and for
    /// an interface, every class implementing it and everything deriving from those.
    /// </summary>
    public IEnumerable<TypeDefinition> Assignable(TypeDefinition type)
    {
        if (!type.IsInterface)
            return SelfAndDerived(type);
        return (_implementers.GetValueOrDefault(type.FullName) ?? []).SelectMany(SelfAndDerived).Distinct();
    }

    /// <summary>The type and its base types, as far as the build defines them.</summary>
    public IEnumerable<TypeDefinition> SelfAndBases(TypeDefinition type)
    {
        var seen = new HashSet<TypeDefinition>();
        for (var current = type; current is not null && seen.Add(current); current = Resolve(current.BaseType))
            yield return current;
    }

    public bool DerivesFrom(TypeDefinition type, string baseFullName) =>
        SelfAndBases(type).Any(x => x.FullName == baseFullName);

    /// <summary>The name a type is indexed and keyed under: the generic type for a generic instance.</summary>
    public static string BaseName(ITypeDescriptor type) => type switch
    {
        TypeSpecification { Signature: GenericInstanceTypeSignature generic } => generic.GenericType.FullName,
        _ => type.FullName,
    };

    /// <summary>The build's definition of a method, or null for one outside the build.</summary>
    public MethodDefinition? Resolve(IMethodDescriptor? method)
    {
        switch (method)
        {
            case null:
                return null;
            case MethodDefinition definition:
                return definition;
            case MethodSpecification specification:
                return Resolve(specification.Method);
        }

        if (method is not MemberReference { Signature: MethodSignature signature } reference || Resolve(reference.DeclaringType as ITypeDefOrRef) is not { } type)
            return null;

        var key = SignatureKey(signature);
        return type.Methods.FirstOrDefault(x => x.Name == reference.Name && x.Signature is { } own && SignatureKey(own) == key);
    }

    /// <summary>The build's definition of a field, or null for one outside the build.</summary>
    public FieldDefinition? Resolve(IFieldDescriptor? field) => field switch
    {
        null => null,
        FieldDefinition definition => definition,
        MemberReference reference when Resolve(reference.DeclaringType as ITypeDefOrRef) is { } type => type.Fields.FirstOrDefault(x => x.Name == reference.Name),
        _ => null,
    };

    /// <summary>A stable key for a method, the same whether it is reached through its definition or a reference.</summary>
    public static string MethodKey(IMethodDescriptor method)
    {
        if (method is MethodSpecification specification)
            method = specification.Method!;
        var declaring = method.DeclaringType is { } type ? BaseName(type) : "";
        return $"{declaring}::{method.Name}({(method.Signature is { } signature ? SignatureKey(signature) : "")})";
    }

    /// <summary>A stable key for a field, the same whether it is reached through its definition or a reference.</summary>
    public static string FieldKey(IFieldDescriptor field)
    {
        var declaring = field.DeclaringType is { } type ? BaseName(type) : "";
        return $"{declaring}::{field.Name}";
    }

    /// <summary>
    /// The parameter types of a signature, generic parameters written by position, so that a reference to
    /// a member of a generic instance matches the definition it points at.
    /// </summary>
    public static string SignatureKey(MethodSignatureBase signature) =>
        string.Join(",", signature.ParameterTypes.Select(x => TypeNames.Format(x, null)));
}
