name: Manual Game Version Update Patch Dispatch

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: guilouro/multiple-repositories-dispatch@master
        with:
          repo_token: ${{secrets.REPO_ACCESS_TOKEN}}
          repositories: |
            BUTR/Bannerlord.ReferenceAssemblies.Documentation
            BUTR/Bannerlord.Harmony
            BUTR/Bannerlord.UIExtenderEx
            BUTR/Bannerlord.ButterLib
            Aragas/Bannerlord.MBOptionScreen
            BUTR/Bannerlord.BLSE
            BUTR/Bannerlord.BUTR.Shared
            BUTR/Bannerlord.Python
            BUTR/Bannerlord.PHP
            BUTR/Bannerlord.DiscordRichPresence
            BUTR/Bannerlord.PlayerSwitcher
            BUTR/Bannerlord.YellToInspire
            BUTR/Bannerlord.ReferenceAssemblies.Diff
          event_type: game_version_update_patch
          client_payload: '{"github": ${{ toJson(github) }}}'
