name: Download

on:
  push:
    branches: 
      - master
  repository_dispatch:
    types:
      - build
  
jobs:
  build:   
    runs-on: windows-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: Setup .NET Core (3.1.100)
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: Build DepotDownloader
      run: dotnet build DepotDownloader/DepotDownloader.sln --configuration Release

    - name: Download
      run: dotnet DepotDownloader/DepotDownloader/bin/Release/netcoreapp2.0/DepotDownloader.dll -app 261550 -depot 261551 -os windows -osarch 64 -username ${{secrets.STEAM_LOGIN}} -password ${{secrets.STEAM_PASSWORD}} -filelist Assemblies.txt
      
