name: Download

on:
  push:
    branches: 
      - master
  repository_dispatch:
    types:
      - build
  
jobs:
  build:   
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: Setup .NET Core (3.1.100)
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: Run
      run: dotnet run --project Bannerlord.ReferenceAssemblies/Bannerlord.ReferenceAssemblies.csproj --configuration Release --login ${{secrets.STEAM_LOGIN}} --pass ${{secrets.STEAM_PASSWORD}} --gtoken ${{secrets.GITHUB_TOKEN}}
