name: Download

on:
  push:
    branches: 
      - master
  repository_dispatch:
    types:
      - build
  
jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/delete-package-versions@v1
      with:
        package-name: Bannerlord.ReferenceAssemblies.Core
        num-old-versions-to-delete: 30
    - uses: actions/delete-package-versions@v1
      with:
        package-name: Bannerlord.ReferenceAssemblies.StoryMode
        num-old-versions-to-delete: 30
    - uses: actions/delete-package-versions@v1
      with:
        package-name: Bannerlord.ReferenceAssemblies.Native
        num-old-versions-to-delete: 30
    - uses: actions/delete-package-versions@v1
      with:
        package-name: Bannerlord.ReferenceAssemblies.CustomBattle
        num-old-versions-to-delete: 30
    - uses: actions/delete-package-versions@v1
      with:
        package-name: Bannerlord.ReferenceAssemblies.SandBox
        num-old-versions-to-delete: 30
